const products=CATALOG_PRODUCTS;
const cats=CATALOG_CATEGORIES;
let cart=JSON.parse(localStorage.getItem("mb-cart")||"[]").map(Number);
const $=id=>document.getElementById(id),money=n=>"₹"+Number(n).toLocaleString("en-IN");
function toast(msg){$("toast").textContent=msg;$("toast").classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>$("toast").classList.remove("show"),2200)}
function renderCats(){ $("catGrid").innerHTML=cats.map(c=>`<div class="cat" onclick="filterCat('${c[1]}')"><span class="icon">${c[0]}</span><div><b>${c[1]}</b><small>${products.filter(p=>p.cat===c[1]).length||"10+"} products</small></div></div>`).join("");$("categoryFilter").innerHTML='<option value="all">All categories</option>'+[...new Set(products.map(p=>p.cat))].map(c=>`<option value="${c}">${c}</option>`).join("")}
function renderProducts(){let q=$("search").value.toLowerCase().trim(),cat=$("categoryFilter").value,arr=products.filter(p=>(!q||[p.name,p.cat,p.sku].join(" ").toLowerCase().includes(q))&&(cat==="all"||p.cat===cat));if($("sort").value==="low")arr.sort((a,b)=>a.price-b.price);if($("sort").value==="high")arr.sort((a,b)=>b.price-a.price);$("resultCount").textContent=`${arr.length} product${arr.length===1?"":"s"} shown`;$("productGrid").innerHTML=arr.slice(0,24).map((p,i)=>`<article class="product" style="animation-delay:${Math.min(i,8)*35}ms"><div class="productImg" onclick="viewProduct(${p.id})"><img src="${p.img}" alt="${p.name}" loading="lazy"></div><div class="productInfo"><span class="tag">${p.cat}</span><h3 onclick="viewProduct(${p.id})">${p.name}</h3><span class="sku">${p.sku}</span><div class="price"><strong>${money(p.price)}</strong><button class="add" onclick="add(${p.id})" aria-label="Add ${p.name}">+</button></div></div></article>`).join("")||'<p>No products found. Try another search.</p>'}
function add(id){cart.push(id);save();openCart();toast("Added to cart")}
function save(){localStorage.setItem("mb-cart",JSON.stringify(cart));renderCart()}
function groupedCart(){return cart.reduce((o,id)=>(o[id]=(o[id]||0)+1,o),{})}
function renderCart(){let grouped=groupedCart();$("cartCount").textContent=cart.length;$("cartItems").innerHTML=Object.entries(grouped).map(([id,q])=>{let p=products.find(x=>x.id==id);return p?`<div class="cartRow"><img src="${p.img}" alt=""><div><h4>${p.name}</h4><div class="qty"><button onclick="change(${p.id},-1)">−</button>${q}<button onclick="change(${p.id},1)">+</button></div></div><b>${money(p.price*q)}</b></div>`:""}).join("")||'<p style="color:#98a2b3;text-align:center;margin-top:50px">Your cart is empty.</p>';let total=cart.reduce((s,id)=>s+(products.find(p=>p.id===id)?.price||0),0);$("subtotal").textContent=money(total);$("checkoutTotal").textContent=money(total);let left=1999-total;$("shipMsg").textContent=left>0?`Add ${money(left)} for free shipping.`:"You qualify for free shipping."}
function change(id,n){if(n>0)cart.push(id);else{let i=cart.indexOf(id);if(i>-1)cart.splice(i,1)}save()}
function filterCat(c){$("categoryFilter").value=c;renderProducts();location.hash="shop"}
function openCart(){$("drawer").classList.add("open");document.body.classList.add("noScroll")}
function closeCart(){$("drawer").classList.remove("open");document.body.classList.remove("noScroll")}
function openModal(id){$(id).classList.add("open");document.body.classList.add("noScroll")}
function closeModal(id){$(id).classList.remove("open");if(!$("drawer").classList.contains("open"))document.body.classList.remove("noScroll")}
function viewProduct(id){let p=products.find(x=>x.id===id);$("productDetail").innerHTML=`<div class="productDetail"><img src="${p.img}" alt="${p.name}"><div><span class="tag">${p.cat}</span><h2>${p.name}</h2><div class="bigPrice">${money(p.price)}</div><div class="detailMeta">SKU: ${p.sku} · Secure checkout · Pan-India delivery</div><p>${p.desc}</p><p>Demo catalogue product. Final specifications, stock and images can be connected to the live Aurelia product database.</p><button class="primary" onclick="add(${p.id});closeModal('productModal')">Add to cart →</button></div></div>`;openModal("productModal")}
function openCheckout(){if(!cart.length){toast("Your cart is empty");return}closeCart();$("checkoutTotal").textContent=$("subtotal").textContent;$("orderSuccess").classList.remove("show");openModal("checkoutModal")}
$("search").addEventListener("input",renderProducts);$("searchBtn").onclick=()=>{renderProducts();location.hash="shop"};$("categoryFilter").onchange=renderProducts;$("sort").onchange=renderProducts;$("cartBtn").onclick=openCart;$("closeCart").onclick=closeCart;$("continue").onclick=closeCart;$("drawer").onclick=e=>{if(e.target===$("drawer"))closeCart()};$("checkout").onclick=openCheckout;
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
document.querySelectorAll(".modal").forEach(m=>m.addEventListener("click",e=>{if(e.target===m)closeModal(m.id)}));
$("checkoutForm").addEventListener("submit",e=>{e.preventDefault();let ref="MB"+Date.now().toString().slice(-8);$("orderSuccess").innerHTML=`<b>Order request created ✓</b><br>Reference: <strong>${ref}</strong><br>Your details were captured in this demo checkout. Connect the backend/payment gateway to place real orders.`;$("orderSuccess").classList.add("show");cart=[];save();e.target.reset();toast("Order request created")});
$("menuBtn").onclick=()=>toast("Use the category links below to browse on mobile");
renderCats();renderProducts();renderCart();
window.addEventListener("DOMContentLoaded",()=>setTimeout(()=>$("loader").classList.add("hide"),120));setTimeout(()=>{const l=$("loader");if(l)l.classList.add("hide")},2500);

const viewed=JSON.parse(localStorage.getItem("mb-viewed")||"[]");
const wishlist=JSON.parse(localStorage.getItem("mb-wishlist")||"[]");
function viewProduct(id){let p=products.find(x=>x.id===id);if(!viewed.includes(id)){viewed.unshift(id);viewed.splice(8);localStorage.setItem("mb-viewed",JSON.stringify(viewed))}$("productDetail").innerHTML=`<div class="productDetail"><img src="${p.img}" alt="${p.name}"><div><span class="tag">${p.cat}</span><h2>${p.name}</h2><div class="bigPrice">${money(p.price)}</div><div class="detailMeta">SKU: ${p.sku} · Secure checkout · Pan-India delivery</div><p>${p.desc}</p><p><b>Delivery:</b> Check availability by PIN at checkout. <br><b>Warranty:</b> Product-dependent. <br><b>Styling:</b> Ask us about this piece on WhatsApp.</p><button class="primary" onclick="add(${p.id});closeModal('productModal')">Add to cart →</button> <a class="secondary" target="_blank" href="https://wa.me/919999999999?text=${encodeURIComponent("Hi Aurelia, I am asking about "+p.name+" ("+p.sku+")")}">Ask on WhatsApp</a><button class="secondary" onclick="toggleWish(${p.id})">♡ Wishlist</button></div></div>`;openModal("productModal")}
function toggleWish(id){let i=wishlist.indexOf(id);if(i>=0)wishlist.splice(i,1);else wishlist.push(id);localStorage.setItem("mb-wishlist",JSON.stringify(wishlist));toast(i>=0?"Removed from wishlist":"Added to wishlist")}
function openTool(id){openModal(id)}
function calcStyleBudget(){const budget=+(document.getElementById("camCount")?.value||2500);const occasion=(document.getElementById("retention")?.value||"Everyday");const category=(document.getElementById("camQuality")?.value||"Earrings");const picks=budget>=5000?"Statement jewellery + clutch + hair accessory":budget>=2500?"Necklace + earrings + bracelet":"Earrings + pendant";const el=document.getElementById("toolResult");if(el)el.innerHTML="For <b>"+occasion+"</b>, try a <b>"+category+"</b> led edit: <b>"+picks+"</b> within ₹"+budget.toLocaleString("en-IN")+"."}
function calcOccasion(){const budget=+(document.getElementById("deviceCount")?.value||3000);const main=document.getElementById("poeCount")?.value||"Necklace";const occasion=document.getElementById("sparePorts")?.value||"Everyday";const el=document.getElementById("networkResult");if(el)el.innerHTML="Look recommendation: <b>"+main+"</b> as the hero piece for a <b>"+occasion+"</b> occasion, with complementary accessories within ₹"+budget.toLocaleString("en-IN")+"."}
function showAccount(tab){let data;if(tab==="orders")data='<b>No real orders yet.</b><br>Your future orders, tracking, invoices and reorder actions will appear here once the backend is connected.';if(tab==="wishlist")data=wishlist.length?wishlist.map(id=>products.find(p=>p.id===id)?.name).filter(Boolean).join("<br>"):"Your wishlist is empty.";if(tab==="recent")data=viewed.length?viewed.map(id=>products.find(p=>p.id===id)?.name).filter(Boolean).join("<br>"):"No recently viewed products.";$("accountContent").innerHTML=data}
$("accountBtn").onclick=()=>{try{const s=JSON.parse(localStorage.getItem("aurelia-session")||"null");location.href=s?.type==="customer"?"account.html":"login.html"}catch(e){location.href="login.html"}};
$("newsletterForm").addEventListener("submit",e=>{e.preventDefault();toast("You're subscribed");e.target.reset()});
$("quoteForm").addEventListener("submit",e=>{e.preventDefault();toast("Style enquiry created");setTimeout(()=>closeModal("quoteModal"),500);e.target.reset()});

function addToCompare(id){let c=JSON.parse(localStorage.getItem("mb-compare")||"[]");if(!c.includes(id)&&c.length<4)c.push(id);localStorage.setItem("mb-compare",JSON.stringify(c));toast(c.length>=4?"Compare list full":"Added to compare")}
function bulkDiscount(total){return 0}
function cartDiscount(){return 0}
function coupon(code,total){const c=String(code||"").trim().toUpperCase();if(c==="WELCOME10"&&total>=2000)return Math.min(total*.1,500);return 0}
function smartProductSearch(q){q=String(q||"").toLowerCase();const nums=q.match(/(?:under|below|less than)\s*₹?\s*(\d+)/);return products.filter(p=>(!nums||p.price<=+nums[1])&&([p.name,p.cat,p.sku,p.desc].join(" ").toLowerCase().includes(q.replace(nums?.[0]||"","").trim())||q.split(/\s+/).every(w=>[p.name,p.cat,p.sku,p.desc].join(" ").toLowerCase().includes(w)))).slice(0,20)}
localStorage.setItem("ar-feature-version","2.0");

/* Aurelia static commerce engine */
const MB={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
function mbOrderTotal(items){return items.reduce((s,x)=>{const p=products.find(p=>p.id==x.id);return s+(p?.price||0)*(x.qty||1)},0)}
function mbGST(total,rate=18){return +(total*rate/100).toFixed(2)}
function mbDelivery(total,pincode){if(!/^\d{6}$/.test(String(pincode||"")))return {ok:false,fee:0,message:"Enter a valid 6-digit pincode"};return {ok:true,fee:total>=1999?0:99,message:total>=1999?"Free delivery":"₹99 delivery"}}
function mbSaveOrder(order){const orders=MB.get("mb-orders",[]);orders.unshift(order);MB.set("mb-orders",orders);MB.set("mb-last-order",order.id);return order}
function mbCreateDemoOrder(data){const id="MB"+Date.now().toString().slice(-8);const subtotal=Number(data.subtotal||0),discount=Number(data.discount||0),shipping=Number(data.shipping||0),gst=mbGST(subtotal-discount);return mbSaveOrder({...data,id,subtotal,discount,shipping,gst,total:subtotal-discount+shipping+gst,status:"Order received",createdAt:new Date().toISOString(),timeline:[["Order received",new Date().toISOString()],["Payment pending",null],["Packed",null],["Shipped",null],["Delivered",null]]})}
function mbExport(key,file){const blob=new Blob([JSON.stringify(MB.get(key,[]),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=file;a.click()}
function mbClearDemoData(){["mb-cart","mb-wishlist","mb-compare","mb-orders","mb-last-order","mb-last-rma","mb-viewed","mb-customer","mb-notifications"].forEach(k=>localStorage.removeItem(k));location.reload()}
function mbNotify(text){const n=MB.get("mb-notifications",[]);n.unshift({text,at:new Date().toISOString(),read:false});MB.set("mb-notifications",n)}
function mbRecordView(id){const v=MB.get("mb-viewed",[]).filter(x=>x!==id);v.unshift(id);MB.set("mb-viewed",v.slice(0,12))}
function mbRecentlyViewed(){return MB.get("mb-viewed",[]).map(id=>products.find(p=>p.id==id)).filter(Boolean)}
function mbGenerateInvoice(order){const lines=["AURELIA — DEMO INVOICE","Order: "+order.id,"Date: "+new Date(order.createdAt).toLocaleString("en-IN"),"Subtotal: ₹"+order.subtotal.toLocaleString("en-IN"),"Discount: ₹"+order.discount.toLocaleString("en-IN"),"GST: ₹"+order.gst.toLocaleString("en-IN"),"Shipping: ₹"+order.shipping.toLocaleString("en-IN"),"TOTAL: ₹"+order.total.toLocaleString("en-IN")];const blob=new Blob([lines.join("\n")],{type:"text/plain"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=order.id+"-invoice.txt";a.click()}


/* AURELIA UX UPGRADE */
const AURELIA_WISHLIST_KEY="mb-wishlist";
function getWish(){try{return JSON.parse(localStorage.getItem(AURELIA_WISHLIST_KEY)||"[]").map(Number)}catch(e){return[]}}
function setWish(a){localStorage.setItem(AURELIA_WISHLIST_KEY,JSON.stringify([...new Set(a)]))}
function toggleWish(id){const a=getWish(),i=a.indexOf(Number(id));if(i>-1)a.splice(i,1);else a.unshift(Number(id));setWish(a);enhancedRender();toast(i>-1?"Removed from wishlist":"Saved to wishlist ♡")}
function wishHas(id){return getWish().includes(Number(id))}
function cardMarkup(p,i){return '<article class="product premiumProduct" style="animation-delay:'+Math.min(i,8)*35+'ms"><div class="productImg"><img src="'+p.img+'" alt="'+p.name+'" loading="lazy" decoding="async"><span class="productBadge">'+(i<6?"NEW":"CURATED")+'</span><button class="wishBtn '+(wishHas(p.id)?"active":"")+'" onclick="event.stopPropagation();toggleWish('+p.id+')" aria-label="Wishlist">'+(wishHas(p.id)?"♥":"♡")+'</button><button class="quickBtn" onclick="event.stopPropagation();viewProduct('+p.id+')">Quick view</button></div><div class="productInfo"><span class="tag">'+p.cat+'</span><h3 onclick="viewProduct('+p.id+')">'+p.name+'</h3><span class="sku">'+p.sku+'</span><div class="rating">★★★★★ <small>('+(8+(p.id%37))+')</small></div><div class="price"><div><strong>'+money(p.price)+'</strong><del>₹'+Math.round(p.price*1.18).toLocaleString("en-IN")+'</del></div><button class="add" onclick="add('+p.id+')">+</button></div></div></article>'}
function enhancedRender(){let q=$("search")?.value.toLowerCase().trim()||"",cat=$("categoryFilter")?.value||"all",arr=products.filter(p=>(!q||[p.name,p.cat,p.sku].join(" ").toLowerCase().includes(q))&&(cat==="all"||p.cat===cat));if($("sort")?.value==="low")arr.sort((a,b)=>a.price-b.price);if($("sort")?.value==="high")arr.sort((a,b)=>b.price-a.price);if($("resultCount"))$("resultCount").textContent=arr.length+" products";if($("productGrid"))$("productGrid").innerHTML=arr.slice(0,24).map(cardMarkup).join("")||'<div class="emptySearch"><b>No perfect match yet.</b><span>Try “pearl”, “bridal”, “earrings” or another category.</span></div>';updateMobileBag();updateSearchSuggest()}
function updateMobileBag(){if($("mobileCartCount"))$("mobileCartCount").textContent=cart.length}
function updateSearchSuggest(){const box=$("searchSuggest"),q=$("search")?.value.trim().toLowerCase();if(!box)return;if(!q){box.classList.remove("show");return}const a=products.filter(p=>[p.name,p.cat,p.sku].join(" ").toLowerCase().includes(q)).slice(0,6);box.innerHTML=a.map(p=>'<button onclick="viewProduct('+p.id+');$("searchSuggest").classList.remove("show")"><img src="'+p.img+'" alt=""><span><b>'+p.name+'</b><small>'+p.cat+' · '+money(p.price)+'</small></span></button>').join("")||'<div class="suggestEmpty">No exact match — try a category or style.</div>';box.classList.add("show")}
function renderRecommendations(){const box=$("smartRecommendations");if(!box)return;const seed=getWish()[0]||1,base=products.find(p=>p.id===seed)||products[0],a=products.filter(p=>p.cat===base.cat&&p.id!==base.id).slice(0,4);box.innerHTML=a.map((p,i)=>cardMarkup(p,i)).join("")}
function giftFind(){const budget=Number($("giftBudget").value),style=$("giftStyle").value.toLowerCase(),words=style==="festive"?["bridal","jhumka","crystal","pearl"]:style==="minimal"?["minimal","classic","everyday"]:style==="statement"?["statement","party","bold"]:["pearl","charm","classic"];let a=products.filter(p=>p.price<=budget&&(words.some(w=>p.name.toLowerCase().includes(w))||p.cat==="Earrings"||p.cat==="Necklaces")).slice(0,4);if(!a.length)a=products.filter(p=>p.price<=budget).slice(0,4);$("giftResults").innerHTML='<div class="finderTitle">Your gift edit</div><div class="finderCards">'+a.map((p,i)=>cardMarkup(p,i)).join("")+'</div>'}
function buildLook(){const main=$("lookMain").value,budget=Number($("lookBudget").value),first=products.filter(p=>p.cat===main).slice(0,1),others=products.filter(p=>p.cat!==main&&p.price<budget).slice(0,5);let a=[...first,...others].slice(0,4);$("lookResults").innerHTML='<div class="finderTitle">Your '+$("lookOcc").value+' edit</div><div class="finderCards">'+a.map((p,i)=>cardMarkup(p,i)).join("")+'</div><button class="primary lookAddAll" onclick="aureliaAddSet()">Add this edit to bag →</button>';window._aureliaSet=a.map(p=>p.id)}
function aureliaAddSet(){(window._aureliaSet||[]).forEach(id=>cart.push(id));save();openCart();toast("Your edit was added to bag")}
function checkPin(){const pin=$("deliveryPin")?.value.trim();const out=$("deliveryResult");if(!out)return;if(!/^[1-9][0-9]{5}$/.test(pin)){out.textContent="Enter a valid 6-digit PIN code.";return}out.innerHTML="<b>Delivery available ✓</b><br>Estimated delivery: 3–5 business days · COD may be available."}
const oldRenderCart=renderCart;
renderCart=function(){oldRenderCart();updateMobileBag();const total=cart.reduce((s,id)=>s+(products.find(p=>p.id===id)?.price||0),0),left=Math.max(0,1999-total),pct=Math.min(100,total/1999*100),msg=$("shipMsg");if(msg)msg.innerHTML=left?'<span>Add '+money(left)+' more for free shipping.</span><div class="shipProgress"><i style="width:'+pct+'%"></i></div>':'<b>You unlocked free shipping ✨</b><div class="shipProgress"><i style="width:100%"></i></div>';const ri=$("cartRecommendations");if(ri){const a=products.filter(p=>!cart.includes(p.id)).slice(0,3);ri.innerHTML=a.map(p=>'<button onclick="add('+p.id+')"><img src="'+p.img+'" alt=""><span>'+p.name+'<b>'+money(p.price)+'</b></span><em>+</em></button>').join("")}}
const oldViewProduct=viewProduct;
viewProduct=function(id){const p=products.find(x=>x.id===id);if(!p)return;mbRecordView?.(id);$("productDetail").innerHTML='<div class="productDetail upgradedDetail"><div><img class="detailHeroImg" src="'+p.img+'" alt="'+p.name+'" loading="eager"><div class="trustStrip"><span>✓ Easy returns</span><span>✓ Gift ready</span><span>✓ Secure checkout</span></div></div><div><span class="tag">'+p.cat+'</span><h2>'+p.name+'</h2><div class="rating bigRating">★★★★★ <small>4.8 · 24 reviews</small></div><div class="bigPrice">'+money(p.price)+' <del>₹'+Math.round(p.price*1.18).toLocaleString("en-IN")+'</del></div><p>'+p.desc+'</p><div class="detailActions"><button class="primary" onclick="add('+p.id+');closeModal(\'productModal\')">Add to bag →</button><button class="secondary" onclick="toggleWish('+p.id+')">'+(wishHas(p.id)?"♥ Saved":"♡ Wishlist")+'</button></div><div class="deliveryCheck"><b>Check delivery</b><div><input id="deliveryPin" inputmode="numeric" maxlength="6" placeholder="Enter PIN code"><button onclick="checkPin()">Check</button></div><small id="deliveryResult">Pan-India delivery · Free shipping over ₹1,999</small></div><div class="productTrust"><span>COD available*</span><span>Gift wrapping</span><span>Easy returns</span></div></div></div>';openModal("productModal")}
document.addEventListener("DOMContentLoaded",()=>{const s=$("search");s?.addEventListener("input",updateSearchSuggest);s?.addEventListener("focus",updateSearchSuggest);document.addEventListener("click",e=>{if(!e.target.closest(".search")&&!e.target.closest(".searchSuggest"))$("searchSuggest")?.classList.remove("show")});$("giftFinderBtn")?.addEventListener("click",()=>openModal("giftFinderModal"));$("lookBuilderBtn")?.addEventListener("click",()=>openModal("lookBuilderModal"));$("giftFind")?.addEventListener("click",giftFind);$("lookBuild")?.addEventListener("click",buildLook);$("mobileBagBtn")?.addEventListener("click",openCart);$("mobileWishBtn")?.addEventListener("click",()=>openModal("accountModal"));$("mobileSearchBtn")?.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"});$("search")?.focus()});enhancedRender();renderRecommendations()});
enhancedRender();
