const products=[
{id:1,name:"8 Port Gigabit Network Switch",cat:"Networking",price:1499,sku:"MB-NET-008",img:"https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=900&q=80",desc:"Compact gigabit switching for home, office and small network setups."},
{id:2,name:"1080p Indoor Wi-Fi Security Camera",cat:"CCTV & Security",price:1899,sku:"MB-CAM-1080",img:"https://images.unsplash.com/photo-1558008258-3256797b43f3?auto=format&fit=crop&w=900&q=80",desc:"A practical indoor security camera concept for monitoring and smart setups."},
{id:3,name:"CAT6 Gigabit Ethernet Cable 20m",cat:"Cables",price:699,sku:"MB-CAT6-020",img:"https://images.unsplash.com/photo-1629654297299-c8506221ca97?auto=format&fit=crop&w=900&q=80",desc:"Long-run Ethernet cable for routers, switches, PCs and CCTV networking."},
{id:4,name:"4K HDMI 2.1 Cable 2m",cat:"Computer Accessories",price:549,sku:"MB-HDMI-4K2",img:"https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=900&q=80",desc:"High-speed HDMI cable concept for modern displays and entertainment systems."},
{id:5,name:"1080p USB Webcam with Mic",cat:"Computer Accessories",price:1299,sku:"MB-WCAM-1080",img:"https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?auto=format&fit=crop&w=900&q=80",desc:"Plug-and-play webcam concept for meetings, calls and streaming."},
{id:6,name:"2.4GHz Wireless Keyboard & Mouse",cat:"Computer Accessories",price:999,sku:"MB-KM-2400",img:"https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80",desc:"Simple wireless keyboard and mouse combo for everyday desktop work."},
{id:7,name:"PoE Injector 48V Gigabit",cat:"Networking",price:899,sku:"MB-POE-048",img:"https://images.unsplash.com/photo-1552913040-189d704b8c16?auto=format&fit=crop&w=900&q=80",desc:"Power-over-Ethernet accessory concept for compatible network devices."},
{id:8,name:"16 Channel NVR Security Recorder",cat:"CCTV & Security",price:8499,sku:"MB-NVR-016",img:"https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=900&q=80",desc:"Multi-channel recorder concept for larger CCTV deployments."},
{id:9,name:"USB-C 65W Fast Charger",cat:"Mobile Accessories",price:1199,sku:"MB-PD-065",img:"https://images.unsplash.com/photo-1592919911506-4d7a3e9d0c9e?auto=format&fit=crop&w=900&q=80",desc:"Compact USB-C power accessory concept for compatible devices."},
{id:10,name:"5-Port USB 3.0 Hub",cat:"Computer Accessories",price:649,sku:"MB-HUB-005",img:"https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=900&q=80",desc:"Expand a computer with additional USB connectivity."},
{id:11,name:"BNC CCTV Connector Pack — 20pc",cat:"CCTV & Security",price:399,sku:"MB-BNC-020",img:"https://images.unsplash.com/photo-1581091870620-fd1a0c4f3c36?auto=format&fit=crop&w=900&q=80",desc:"Connector pack concept for CCTV installation and maintenance."},
{id:12,name:"12V 5A CCTV Power Supply",cat:"CCTV & Security",price:799,sku:"MB-PSU-125",img:"https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=900&q=80",desc:"Power supply concept for compatible CCTV hardware."}
];
const cats=[["⌁","Networking"],["◉","CCTV & Security"],["▤","Cables"],["⌨","Computer Accessories"],["⚡","Mobile Accessories"],["◈","Tools & Power"]];
let cart=JSON.parse(localStorage.getItem("mb-cart")||"[]").map(Number);
const $=id=>document.getElementById(id),money=n=>"₹"+Number(n).toLocaleString("en-IN");
function toast(msg){$("toast").textContent=msg;$("toast").classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>$("toast").classList.remove("show"),2200)}
function renderCats(){ $("catGrid").innerHTML=cats.map(c=>`<div class="cat" onclick="filterCat('${c[1]}')"><span class="icon">${c[0]}</span><div><b>${c[1]}</b><small>${products.filter(p=>p.cat===c[1]).length||"10+"} products</small></div></div>`).join("");$("categoryFilter").innerHTML='<option value="all">All categories</option>'+[...new Set(products.map(p=>p.cat))].map(c=>`<option value="${c}">${c}</option>`).join("")}
function renderProducts(){let q=$("search").value.toLowerCase().trim(),cat=$("categoryFilter").value,arr=products.filter(p=>(!q||[p.name,p.cat,p.sku].join(" ").toLowerCase().includes(q))&&(cat==="all"||p.cat===cat));if($("sort").value==="low")arr.sort((a,b)=>a.price-b.price);if($("sort").value==="high")arr.sort((a,b)=>b.price-a.price);$("resultCount").textContent=`${arr.length} product${arr.length===1?"":"s"} shown`;$("productGrid").innerHTML=arr.map((p,i)=>`<article class="product" style="animation-delay:${Math.min(i,8)*35}ms"><div class="productImg" onclick="viewProduct(${p.id})"><img src="${p.img}" alt="${p.name}" loading="lazy"></div><div class="productInfo"><span class="tag">${p.cat}</span><h3 onclick="viewProduct(${p.id})">${p.name}</h3><span class="sku">${p.sku}</span><div class="price"><strong>${money(p.price)}</strong><button class="add" onclick="add(${p.id})" aria-label="Add ${p.name}">+</button></div></div></article>`).join("")||'<p>No products found. Try another search.</p>'}
function add(id){cart.push(id);save();openCart();toast("Added to cart")}
function save(){localStorage.setItem("mb-cart",JSON.stringify(cart));renderCart()}
function groupedCart(){return cart.reduce((o,id)=>(o[id]=(o[id]||0)+1,o),{})}
function renderCart(){let grouped=groupedCart();$("cartCount").textContent=cart.length;$("cartItems").innerHTML=Object.entries(grouped).map(([id,q])=>{let p=products.find(x=>x.id==id);return p?`<div class="cartRow"><img src="${p.img}" alt=""><div><h4>${p.name}</h4><div class="qty"><button onclick="change(${p.id},-1)">−</button>${q}<button onclick="change(${p.id},1)">+</button></div></div><b>${money(p.price*q)}</b></div>`:""}).join("")||'<p style="color:#98a2b3;text-align:center;margin-top:50px">Your cart is empty.</p>';let total=cart.reduce((s,id)=>s+(products.find(p=>p.id===id)?.price||0),0);$("subtotal").textContent=money(total);$("checkoutTotal").textContent=money(total);let left=1999-total;$("shipMsg").textContent=left>0?`Add ${money(left)} for free shipping.`:"You qualify for free shipping."}
function change(id,n){if(n>0)cart.push(id);else{let i=cart.indexOf(id);if(i>-1)cart.splice(i,1)}save()}
function filterCat(c){$("categoryFilter").value=c;renderProducts();location.hash="shop"}
function openCart(){$("drawer").classList.add("open");document.body.classList.add("noScroll")}
function closeCart(){$("drawer").classList.remove("open");document.body.classList.remove("noScroll")}
function openModal(id){$(id).classList.add("open");document.body.classList.add("noScroll")}
function closeModal(id){$(id).classList.remove("open");if(!$("drawer").classList.contains("open"))document.body.classList.remove("noScroll")}
function viewProduct(id){let p=products.find(x=>x.id===id);$("productDetail").innerHTML=`<div class="productDetail"><img src="${p.img}" alt="${p.name}"><div><span class="tag">${p.cat}</span><h2>${p.name}</h2><div class="bigPrice">${money(p.price)}</div><div class="detailMeta">SKU: ${p.sku} · GST invoice available · Pan-India delivery</div><p>${p.desc}</p><p>Demo catalogue product. Final specifications, stock and images can be connected to the live MultiByte product database.</p><button class="primary" onclick="add(${p.id});closeModal('productModal')">Add to cart →</button></div></div>`;openModal("productModal")}
function openCheckout(){if(!cart.length){toast("Your cart is empty");return}closeCart();$("checkoutTotal").textContent=$("subtotal").textContent;$("orderSuccess").classList.remove("show");openModal("checkoutModal")}
$("search").addEventListener("input",renderProducts);$("searchBtn").onclick=()=>{renderProducts();location.hash="shop"};$("categoryFilter").onchange=renderProducts;$("sort").onchange=renderProducts;$("cartBtn").onclick=openCart;$("closeCart").onclick=closeCart;$("continue").onclick=closeCart;$("drawer").onclick=e=>{if(e.target===$("drawer"))closeCart()};$("checkout").onclick=openCheckout;
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
document.querySelectorAll(".modal").forEach(m=>m.addEventListener("click",e=>{if(e.target===m)closeModal(m.id)}));
$("checkoutForm").addEventListener("submit",e=>{e.preventDefault();let ref="MB"+Date.now().toString().slice(-8);$("orderSuccess").innerHTML=`<b>Order request created ✓</b><br>Reference: <strong>${ref}</strong><br>Your details were captured in this demo checkout. Connect the backend/payment gateway to place real orders.`;$("orderSuccess").classList.add("show");cart=[];save();e.target.reset();toast("Order request created")});
$("menuBtn").onclick=()=>toast("Use the category links below to browse on mobile");
renderCats();renderProducts();renderCart();
window.addEventListener("load",()=>setTimeout(()=>$("loader").classList.add("hide"),500));

const viewed=JSON.parse(localStorage.getItem("mb-viewed")||"[]");
const wishlist=JSON.parse(localStorage.getItem("mb-wishlist")||"[]");
function viewProduct(id){let p=products.find(x=>x.id===id);if(!viewed.includes(id)){viewed.unshift(id);viewed.splice(8);localStorage.setItem("mb-viewed",JSON.stringify(viewed))}$("productDetail").innerHTML=`<div class="productDetail"><img src="${p.img}" alt="${p.name}"><div><span class="tag">${p.cat}</span><h2>${p.name}</h2><div class="bigPrice">${money(p.price)}</div><div class="detailMeta">SKU: ${p.sku} · GST invoice available · Pan-India delivery</div><p>${p.desc}</p><p><b>Delivery:</b> Check availability by PIN at checkout. <br><b>Warranty:</b> Product-dependent. <br><b>Bulk:</b> Ask for a quote on WhatsApp.</p><button class="primary" onclick="add(${p.id});closeModal('productModal')">Add to cart →</button> <a class="secondary" target="_blank" href="https://wa.me/919999999999?text=${encodeURIComponent("Hi MultiByte, I am asking about "+p.name+" ("+p.sku+")")}">Ask on WhatsApp</a><button class="secondary" onclick="toggleWish(${p.id})">♡ Wishlist</button></div></div>`;openModal("productModal")}
function toggleWish(id){let i=wishlist.indexOf(id);if(i>=0)wishlist.splice(i,1);else wishlist.push(id);localStorage.setItem("mb-wishlist",JSON.stringify(wishlist));toast(i>=0?"Removed from wishlist":"Added to wishlist")}
function openTool(id){openModal(id)}
function calcCCTV(){let c=+$("camCount").value,h=+$("recHours").value,d=+$("retention").value,q=+$("camQuality").value;let gb=c*h*d*q;let usable=Math.ceil(gb*1.2);$("toolResult").innerHTML=`Estimated requirement: <b>~${usable} GB</b> (${(usable/1024).toFixed(1)} TB). We added ~20% practical headroom.`}
function calcNetwork(){let d=+$("deviceCount").value,p=+$("poeCount").value,s=+$("sparePorts").value,total=d+s;let size=total<=5?5:total<=8?8:total<=16?16:24;let poe=p?Math.max(p,4):0;$("networkResult").innerHTML=`Recommendation: <b>${size}-port switch</b>${poe?` with at least <b>${poe} PoE ports</b>`:""} plus ${s} spare ports. Final switch model should be selected based on actual PoE wattage and uplink requirements.`}
function showAccount(tab){let data;if(tab==="orders")data='<b>No real orders yet.</b><br>Your future orders, tracking, invoices and reorder actions will appear here once the backend is connected.';if(tab==="wishlist")data=wishlist.length?wishlist.map(id=>products.find(p=>p.id===id)?.name).filter(Boolean).join("<br>"):"Your wishlist is empty.";if(tab==="recent")data=viewed.length?viewed.map(id=>products.find(p=>p.id===id)?.name).filter(Boolean).join("<br>"):"No recently viewed products.";$("accountContent").innerHTML=data}
$("accountBtn").onclick=()=>{showAccount("orders");openModal("accountModal")};
$("newsletterForm").addEventListener("submit",e=>{e.preventDefault();toast("You're subscribed");e.target.reset()});
$("quoteForm").addEventListener("submit",e=>{e.preventDefault();toast("Bulk enquiry created");setTimeout(()=>closeModal("quoteModal"),500);e.target.reset()});

function addToCompare(id){let c=JSON.parse(localStorage.getItem("mb-compare")||"[]");if(!c.includes(id)&&c.length<4)c.push(id);localStorage.setItem("mb-compare",JSON.stringify(c));toast(c.length>=4?"Compare list full":"Added to compare")}
function bulkDiscount(total){return total>=25000?.07:total>=10000?.03:0}
function cartDiscount(){const total=cart.reduce((s,id)=>s+(products.find(p=>p.id===id)?.price||0),0);return bulkDiscount(total)}
function coupon(code,total){const c=String(code||"").trim().toUpperCase();if(c==="WELCOME10"&&total>=2000)return Math.min(total*.1,500);if(c==="BULK5"&&total>=5000)return total*.05;return 0}
function smartProductSearch(q){q=String(q||"").toLowerCase();const nums=q.match(/(?:under|below|less than)\s*₹?\s*(\d+)/);return products.filter(p=>(!nums||p.price<=+nums[1])&&([p.name,p.cat,p.sku,p.desc].join(" ").toLowerCase().includes(q.replace(nums?.[0]||"","").trim())||q.split(/\s+/).every(w=>[p.name,p.cat,p.sku,p.desc].join(" ").toLowerCase().includes(w)))).slice(0,20)}
localStorage.setItem("mb-feature-version","2.0");

/* MultiByte static commerce engine */
const MB={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
function mbOrderTotal(items){return items.reduce((s,x)=>{const p=products.find(p=>p.id==x.id);return s+(p?.price||0)*(x.qty||1)},0)}
function mbGST(total,rate=18){return +(total*rate/100).toFixed(2)}
function mbDelivery(total,pincode){if(!/^\d{6}$/.test(String(pincode||"")))return {ok:false,fee:0,message:"Enter a valid 6-digit pincode"};return {ok:true,fee:total>=1999?0:99,message:total>=1999?"Free delivery":"₹99 delivery"}}
function mbSaveOrder(order){const orders=MB.get("mb-orders",[]);orders.unshift(order);MB.set("mb-orders",orders);MB.set("mb-last-order",order.id);return order}
function mbCreateDemoOrder(data){const id="MB"+Date.now().toString().slice(-8);const subtotal=Number(data.subtotal||0),discount=Number(data.discount||0),shipping=Number(data.shipping||0),gst=mbGST(subtotal-discount);return mbSaveOrder({...data,id,subtotal,discount,shipping,gst,total:subtotal-discount+shipping+gst,status:"Order received",createdAt:new Date().toISOString(),timeline:[["Order received",new Date().toISOString()],["Payment pending",null],["Packed",null],["Shipped",null],["Delivered",null]]})}
function mbExport(key,file){const blob=new Blob([JSON.stringify(MB.get(key,[]),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=file;a.click()}
function mbClearDemoData(){["mb-cart","mb-wishlist","mb-compare","mb-orders","mb-last-order","mb-last-rma","mb-viewed","mb-customer","mb-notifications"].forEach(k=>localStorage.removeItem(k));location.reload()}
function mbNotify(text){const n=MB.get("mb-notifications",[]);n.unshift({text,at:new Date().toISOString(),read:false});MB.set("mb-notifications",n)}
function mbRecordView(id){const v=MB.get("mb-viewed",[]).filter(x=>x!==id);v.unshift(id);MB.set("mb-viewed",v.slice(0,12))}
function mbRecentlyViewed(){return MB.get("mb-viewed",[]).map(id=>products.find(p=>p.id==id)).filter(Boolean)}
function mbGenerateInvoice(order){const lines=["MULTIBYTE — DEMO INVOICE","Order: "+order.id,"Date: "+new Date(order.createdAt).toLocaleString("en-IN"),"Subtotal: ₹"+order.subtotal.toLocaleString("en-IN"),"Discount: ₹"+order.discount.toLocaleString("en-IN"),"GST: ₹"+order.gst.toLocaleString("en-IN"),"Shipping: ₹"+order.shipping.toLocaleString("en-IN"),"TOTAL: ₹"+order.total.toLocaleString("en-IN")];const blob=new Blob([lines.join("\n")],{type:"text/plain"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=order.id+"-invoice.txt";a.click()}
